### ISSUE TITLE
No function called?

### ISSUE THREAD

**Issue by Jackobli** [maloja/pico-fotofolder#1]
Hi
Just installed a fresh Ubuntu 20.04 LTS (focal) with apache2 and php 7.4
installed picocms and pico-fotofolder through composer.
But if I use your example:
`(% fotofolder ( %assets_url%/test %)`
It just puts a:
(% fotofolder ( http://picotest/pico/assets/test %)
on the rendered website.
What do I miss with your plugin?
No errors in error.log of apache.

**Comment by maloja** [comment]
Placeholder like %assets_url% are currently not supported. In the meantime, please use the relative path to your images e.g. `/pico/assets/test` or `/assets/test.`

**Comment by Jackobli** [comment]
Ok, thank you for your info, but adding the path instead of the placeholder just echoes text. It triggers no execution of any js or so.
(% fotofolder ( /html/pico/assets/test %)
I also tried the whole path as html link. But this creates just a regular link and triggers a directory listing (which is actually allowed in my config on this test machine).

**Comment by maloja** [comment]
There's still a closing bracket missing in your example right after the path

(% fotofolder (/assets/test**)** %)

**Comment by Jackobli** [comment]
Thank you, that solved it somehow (not) ;-)
Your example in the readme.md says.

`(% fotofolder ( /path/to/your/images [sort] [order] `%)`
**So perhaps adding the bracket there would prevent another newby to stumble over that.**

Now the page shows blank and the error log is complaining:

`[Fri Aug 14 19:11:28.859007 2020] [php7:error] [pid 20075] [client 192.168.0.23:55564] PHP Fatal error:  Uncaught Error: Call to undefined function imagecreatefromjpeg() in /var/www/html/pico/plugins/PicoFotofolder/PicoFotofolder.php:191\nStack trace:\n#0 /var/www/html/pico/plugins/PicoFotofolder/PicoFotofolder.php(113): PicoFotofolder->scaleImageCopy()\n#1 /var/www/html/pico/plugins/PicoFotofolder/PicoFotofolder.php(42): PicoFotofolder->readMetaArray()\n#2 [internal function]: PicoFotofolder->{closure}()\n#3 /var/www/html/pico/plugins/PicoFotofolder/PicoFotofolder.php(50): preg_replace_callback()\n#4 /var/www/html/pico/vendor/picocms/pico/lib/AbstractPicoPlugin.php(101): PicoFotofolder->onContentParsed()\n#5 /var/www/html/pico/plugins/PicoDeprecated/PicoDeprecated.php(319): AbstractPicoPlugin->handleEvent()\n#6 /var/www/html/pico/plugins/PicoDeprecated/lib/AbstractPicoPluginApiCompatPlugin.php(81): PicoDeprecated->triggerEvent()\n#7 /var/www/html/pico/plugins/PicoDeprecated/lib/AbstractPicoPluginApiCompatPlugin.php(49): AbstractPicoPluginApiCompatPlugin->triggerEvent()\n#8 /var/www/html/pico/plugins/PicoDeprecated/PicoDe in /var/www/html/pico/plugins/PicoFotofolder/PicoFotofolder.php on line 191`

That did look like there were a jpg library missing and bingo, installing php-gd solved the problem. 
Everything fine now.

**Comment by maloja** [comment]
Hi
Thanks for pointing out the missing bracket on the readme.md page as well as the GD library hint. I'll correct the information asap.

**Comment by Jackobli** [comment]
Thank you for your support.
